### ISSUE TITLE
New Feature: Normal form for symmetric monoidal categories

### ISSUE THREAD

**Issue by y-richie-y** [oxford-quantum-group/discopy#16]
Currently `diagram.normal_form()` only applies normal form to monoidal categories.
As a first step towards a symmetric monoidal normal form, we should just remove all double swaps and apply the Yang-Baxter equation from left to right.

**Comment by toumix** [comment]
Closing this issue as it's now part of the bigger issue https://github.com/oxford-quantum-group/discopy/issues/25.
