### ISSUE TITLE
Symbolic arrays for parametrised quantum gates

### ISSUE THREAD

**Issue by toumix** [oxford-quantum-group/discopy#19]
It should be possible to compute the array of a parametrised quantum gate.
We need to use sympy's exponential function, etc. instead of numpy whenever the gate has free symbols.

**Comment by aljabr0** [comment]
Just to complete the discussion started in the pull request, it remains to check that limit situations like this:
```python
sy.sympify(1+sy.sqrt(2)).free_symbols
```
where the set returned by `free_symbols` is empty but the numeric value is still incompatible with numpy primitives, are handled correctly.
Thanks
