### ISSUE TITLE
quantum.circuit.Sum behaviour different between 1 and n arguments

### ISSUE THREAD

**Issue by aljabr0** [oxford-quantum-group/discopy#22]
Hi, I found the following unexpected behaviour of the entity mentioned in the subject, here the first case:
```python
from discopy.quantum import *
Sum([Id(1), Id(1)], dom=qubit, cod=qubit).eval()
```
This returns `Tensor(dom=Dim(2), cod=Dim(2), array=[2., 0., 0., 2.])`, also the same result can be obtained through
`sum([Id(1), Id(1)]).eval()` and `(Id(1) + Id(1)).eval()`.

Instead, if we pass a list containing a single term
```python
Sum([Id(1)], dom=qubit, cod=qubit).eval()
```
we obtain `array([1., 1.])` (same result with `sum([Id(1)]).eval()` and `(Id(1)+0).eval()`).
According to my understanding the second case should return something like `Tensor(dom=Dim(2), cod=Dim(2), array=[1., 0., 0., 1.])`, that is the result of `Id(1).eval()`.
Thanks

**Comment by toumix** [comment]
Good catch! Commit 35fa452 now fixes this.
