### ISSUE TITLE
Controlled gates between non-adjacent qubits.

### ISSUE THREAD

**Issue by toumix** [oxford-quantum-group/discopy#28]
We need controlled gates between non-adjacent qubits, so that we don't clutter our diagrams with swaps. That is, we want an abstract base class:
```python
ControlledGate(controlled, target=0)
```
where `controlled` is a gate, e.g. `CX = ControlledGate(X)`, and `target` is an int that specifies the relative position of the target w.r.t the control qubit.

If we set `target >= 0` then there is `target` qubit wires running between control on the left and target on the right.
If we set `target < 0` then the control is on the right of the target instead.

We also want these new boxes to be drawn nicely, see issue https://github.com/oxford-quantum-group/discopy/issues/27.

**Comment by aljabr0** [comment]
Hi, I have been working on something similar, in my case for CX only, see `ext_cx` on https://github.com/aljabr0/discopy/blob/real_amp_ansatz/discopy/quantum/gates.py
However it's still uncompleted and untested.
