### ISSUE TITLE
Conjugation of diagrams

### ISSUE THREAD

**Issue by toumix** [oxford-quantum-group/discopy#35]
DisCoPy already has a dagger method, implementing the vertical reflection of a diagram.
It would be useful to also have horizontal reflections, i.e. diagrammatic conjugation.

This requires each box to hold two Booleans, `_dagger` and `_conjugate`.
Setting `_dagger = _conjugate = True` we get the diagrammatic transpose for free.

**Comment by y-richie-y** [comment]
resolved by #44
