### ISSUE TITLE
Memory overflow when using backend=AerBackend()

### ISSUE THREAD

**Issue by Thommy257** [oxford-quantum-group/discopy#40]
Hey,
I came across a weird memory leak when using the AerBackend. Here's a minimal example to reproduce:

```python
import os, psutil
from random import random
from discopy.quantum import Ket, Rz, Rx, Circuit
from pytket.extensions.qiskit import AerBackend

process = psutil.Process(os.getpid())


def verb_ansatz(p):
    return Ket(0) >> Rx(p)

def noun_ansatz(p):
    return Ket(0) >> Rz(p)

def eval(backend = AerBackend()):

    circuits = [verb_ansatz(random()) >> noun_ansatz(random()).dagger() for i in range(10)]
    results = [
        Circuit.eval(
            circuit,
            backend=backend,
            n_shots=2**10,
            seed=0,
            compilation=backend.default_compilation_pass(2))
             for circuit in circuits
        ]

    return results

if __name__=="__main__":
    i = 0
    while True:
        f = eval()
        i+=1
        print(i,psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
```

It appears that the backend variable accumulates memory over time, eventually leading to an overflow. A solution that worked for me was to initialize the backend every time in the ```eval()``` function:

```python
def eval():

    backend = AerBackend()
    circuits = [verb_ansatz(random()) >> noun_ansatz(random()).dagger() for i in range(10)]
    results = [
        Circuit.eval(
            circuit,
            backend=backend,
            n_shots=2**10,
            seed=0,
            compilation=backend.default_compilation_pass(2))
             for circuit in circuits
        ]

    return results

```

I'm not sure if this is optimal but it seems to fix the memory leak. 

I'm sending you this because I've seen the above syntax in the qnlp-experiment notebook.

**Comment by toumix** [comment]
Thanks for raising the issue! It's a very strange bug indeed.

I can't see where the memory leak could happen on the DisCoPy side, but weirdly enough I didn't manage to reproduce the bug using tket only. It could be that the tket backend keeps track of all the previous shots? I'll investigate and come back to you, in the meantime I think your fix makes sense.

**Comment by toumix** [comment]
Ok I haven't managed to figure out where the bug comes from but I edited the notebook so that it doesn't use the syntax with AerBackend() as default argument anymore, see commit https://github.com/oxford-quantum-group/discopy/commit/3eb9171accfa860b4d4849b78682ccd31ca6a51a.
