### ISSUE TITLE
Extension of tk.Circuit applies same scalar to all circuits passed in

### ISSUE THREAD

**Issue by oneTimePad** [oxford-quantum-group/discopy#43]
In `tk.py` on line 134, the `scalar` of `self` is being applied to the results of all circuits passed in, including the list of `others`. The `scalar` properties of the circuits in `others` are being ignored. Thus the `scalar` of only the first circuit in the list is considered.

snippet form tk.py (131 - 134):
```        
if scale:
    for i, _ in enumerate((self, ) + others):
          for bitstring in counts[i]:
               counts[i][bitstring] *= self.scalar <- I don't think this is intended.
```

I believe this is not intended.

**Comment by toumix** [comment]
Good catch!
I guess we never noticed this because we were always using lists of circuits with the same scalars.
It should have been:
```python
if scale:
    for i, circuit in enumerate((self, ) + others):
        for bitstring in counts[i]:
            counts[i][bitstring] *= circuit.scalar
```
This is now fixed by commit https://github.com/oxford-quantum-group/discopy/commit/4a6a13c9f41a61b49e62124fee6f6d57c59982bf .
