### ISSUE TITLE
Dynamically compose a sequence

### ISSUE THREAD

**Issue by hwazni** [oxford-quantum-group/discopy#48]
Hi, is there a function that appends **>>** in a dynamic way ? 

For example, I have a list of grammars / diagrams:
glist = [g1, g2, g3, g4]

I want the result = g1 >> g2 >> g3 >> g4

It's similar to a for loop: 

for g in glist: 
    result + >> g

Thanks.

**Comment by toumix** [comment]
Hi, the `then` method of `cat.Arrow` (which is then overriden by `monoidal.Diagram`, etc.) accepts any number of arguments, or indeed a list of arguments using the Python star notation. You can either call `then` from the first diagram you're composing, or from an identity diagram, or from the `Diagram` class directly.

```
g1.then(g2, g3, g4) == Id(g1.dom).then(*glist) == Diagram.then(*glist)
```
