### ISSUE TITLE
AxiomError while trying to adapt a tutorial

### ISSUE THREAD

**Issue by alt-shreya** [oxford-quantum-group/discopy#86]
Hey everyone, I'm new to QNLP. I recently discovered [this tutorial](https://discopy.readthedocs.io/en/main/notebooks/qnlp-tutorial.html) on the DisCoPy docs website. I want to adapt this to my own blog tutorial. 

To add a little variation, I'm following an eggless recipe of crema di mascarpone, replacing the yolk with yoghurt and the whites with a little applesauce. 
Warning: I haven't tested this recipe.
With the magic of quantum computers, I have the possibility of executing this experiment virtually.

The process followed would be a little different as there would be no process to crack an egg. Instead, the directions would be as follows:

1. **Beat** **sugar** and **yoghurt** together to make a **yoghurt mix**.
2. **Stir** a little **applesauce** with **mascarpone cheese**.
3. **Fold** the mixture of **yoghurt mix** and **stirred mascarpone cheese** to get **crema di mascarpone**.

Here's the diagrammatic representation of it
![image](https://user-images.githubusercontent.com/70858293/185560668-f6823779-a119-4207-94c8-1ba8b828453a.png)

Here's the code I have tried to implement:

Method 1

````
from discopy import Ob, Ty, Id, Box

yoghurt, milk, = Ty('yoghurt'), Ty('milk')

assert yoghurt.objects == [Ob('yoghurt')]
assert yoghurt @ Ty() == yoghurt == Ty() @ yoghurt
sugar = Ty('sugar')
assert yoghurt @ sugar == Ty(Ob('yoghurt'), Ob('sugar'))
yoghurty_paste = Ty('yoghurty_paste')
beat = Box('beat', yoghurt @ sugar, yoghurty_paste)
beat.draw(aspect='auto')
````

Method 2
````
from discopy import Ty, Box, Id

mixture, yoghurt, applesauce = Ty('mixture'), Ty('yoghurt'), Ty('applesauce')
sugar, mascarpone = Ty('sugar'), Ty('mascarpone')
yoghurty_paste, thick_paste = Ty('yoghurty_paste'), Ty('thick_paste')
crema_di_mascarpone = Ty('crema_di_mascarpone')

sep2 = Box('separate', mixture, yoghurt @ applesauce)
beat2 = Box('beat', yoghurt @ sugar, yoghurty_paste)
whisk2 = Box('whisk', applesauce, applesauce)
stir2 = Box('stir', yoghurty_paste @ mascarpone, thick_paste)
fold2 = Box('fold', applesauce @ thick_paste, crema_di_mascarpone)


recipe2 = Id(sugar) @ Id(yoghurt) @ Id(applesauce) @ Id(mascarpone)\
        >> beat2 @ Id(applesauce) @ Id(mascarpone)

recipe2.draw(aspect='auto')
````
`AxiomError: Id(sugar @ yoghurt @ applesauce @ mascarpone) does not compose with beat @ Id(applesauce @ mascarpone).
`

I'd appreciate any help/ direction to resources that can make this clearer.

Thank you so much!

**Comment by y-richie-y** [comment]
Welcome!

`beat2 @ Id(applesauce) @ Id(mascarpone)` has domain `Ty('yoghurt', 'sugar', 'applesauce', 'mascarpone')`, which mismatches the output of the identity diagram `Id(sugar) @ Id(yoghurt) @ Id(applesauce) @ Id(mascarpone)`, which has codomain `Ty('sugar', 'yoghurt', 'applesauce', 'mascarpone')`.

You also seem to have mistyped `stir2`, using `yoghurty_paste` instead of `applesauce`.

Also, it is not necessary to start with the identity diagram, it can be removed.

**Comment by y-richie-y** [comment]
Marking this as closed unless there is new activity.
